algoritmo "função_Pos_Neg"
// Função : Recebe um argumento e retorna "P" caso positivo e "N" caso negativo
// Autor : grupo 4
// Data : 7/5/2013
// Seção de Declarações

var
// Declaração de variáveis
valor_1, valor:inteiro



procedimento valor

inicio

se (valor_1>0) entao
escreval (" P ")
senao
escreval (" N ")
fimse

fimprocedimento

inicio

// Seção de Comandos
escreva("Entre com o valor: ") // Imprime na tela o texto
leia (valor_1)   // lê o valor digitado

valor ()

fimalgoritmo
