algoritmo "semnome"
// Função : Recebe 4 notas e mostra a media
// Autor :
// Data : 5/6/2013
// Seção de Declarações 
var
n1, n2, n3, n4, media:real
inicio
// Seção de Comandos
escreval ("Insira a nota 1: ")
leia (n1)
escreval ("Insira a nota 2: ")
leia (n2)
escreval ("Insira a nota 3: ")
leia (n3)
escreval ("Insira a nota 4: ")
leia (n4)
media <- n1 + n2 + n3 + n4
media <- media /4
escreval ("A media e",media)
fimalgoritmo
