algoritmo "area_quadrado"
// Função : calcula a area do quadrado e multiplica por 2
// Autor : grupo 4
// Data : 7/5/2013
// Seção de Declarações

var
// Declaração de variáveis
l:real
inicio
// Seção de Comandos
escreval("Entre com o lado do quadrado:") // Imprime na tela o texto
leia(l)  // lê o valor digitado

l <- l*l   // calcula a area do quadrado
l <- l*2   // multiplica por 2 a area

escreval("O dobro da área é: ",l)  // escreve o resultado

fimalgoritmo
